-- Migration V14.1: Fix ID sequence para site_profile
-- Resolve o erro "null value in column id violates not-null constraint"
-- que ocorreu devido a remoção do DEFAULT na V12.

-- Adiciona a propriedade de identidade (auto-incremento nativo do Postgres)
-- caso a coluna seja INT ou BIGINT.
ALTER TABLE public.site_profile 
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
